version: "3"

services:
  web:
    image: nginx
    volumes:
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./conf/conf.d:/etc/nginx/conf.d:ro
      - ./conf/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "443:443"
      - "80:80"
    links:
      - wetty
      - portainer
    networks:
      - mgmt

  wetty:
    image: orangeswim/wetty
    build: ./wetty/
    expose:
      - "3000"
    volumes:
      - ./conf/lshell.conf:/etc/lshell.conf:ro


  portainer:
    image: portainer/portainer
    expose:
      - "9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  outside:
    image: centos
    networks:
      - mgmt
    entrypoint: /bin/bash

volumes:
  portainer_data:
networks:
  mgmt:
